import { createContext, useContext, type ReactNode } from "react";

export type Language = "sv" | "no" | "da" | "fi" | "en";

export type HotelPreferencesValue = {
  language: Language;
  senior: boolean;
  setLanguage: (language: Language) => void;
  setSenior: (senior: boolean) => void;
};

const HotelPreferencesContext = createContext<HotelPreferencesValue | null>(null);

export function HotelPreferencesProvider({ children, value }: { children: ReactNode; value: HotelPreferencesValue }) {
  return <HotelPreferencesContext.Provider value={value}>{children}</HotelPreferencesContext.Provider>;
}

export function useHotelPreferences() {
  const context = useContext(HotelPreferencesContext);
  if (!context) throw new Error("useHotelPreferences must be used inside HotelPreferencesProvider");
  return context;
}

export const languageNames: Record<Language, string> = {
  sv: "Svenska",
  no: "Norsk",
  da: "Dansk",
  fi: "Suomi",
  en: "English",
};

type Copy = {
  location: string; intro: string; rooms: string; altitude: string; cat: string;
  guestService: string; safety: string; about: string; duringStay: string; privacyTitle: string; privacyBody: string;
  hildurLabel: string; online: string; greeting: string; seniorGreeting: string; ask: string; send: string;
  actions: [string, string, string, string, string, string]; tabs: [string, string, string];
  bookingHello: string; arrival: string; departure: string; guests: string; availability: string; next: string; back: string;
  manageHello: string; reference: string; findBooking: string; checkHello: string; roomNumber: string; checkIn: string; checkOut: string;
  seniorMode: string; seniorHint: string; navMenu: string; language: string;
  sauna: string; saunaSub: string; breakfast: string; breakfastSub: string; aurora: string; auroraSub: string; issue: string; issueSub: string;
  book: string; yourTime: string; full: string; spots: string; seating: string; dietary: string; reserve: string; date: string; people: string; spotsLeft: string;
  issueRoom: string; category: string; description: string; sendIssue: string;
};

export const copy: Record<Language, Copy> = {
  sv: {
    location: "Hemavan · Södra Lappland", intro: "Trettioåtta rum, en sprakande bastu och fjället utanför fönstret. Här tar vi emot dig med varm fjällgästfrihet – och en katt som heter Kjell.", rooms: "rum", altitude: "m ö.h.", cat: "hotellkatt",
    guestService: "Gästservice", safety: "Trygghet", about: "Om oss", duringStay: "Under vistelsen", privacyTitle: "Dina uppgifter är trygga hos oss", privacyBody: "Precis som Birgitta låser ytterdörren varje kväll, vaktar Hildur dina uppgifter. Vi följer GDPR och du kan alltid be oss visa eller radera det vi sparat.",
    hildurLabel: "Digital receptionist", online: "Här dygnet runt", greeting: "Hej! Jag är Hildur. Jag tar hand om det praktiska, så att Birgitta kan lägga all sin tid på varm fjällgästfrihet. Vad kan jag hjälpa dig med?", seniorGreeting: "Hej kära du! Vi tar en sak i taget, lugnt och enkelt. Kjell håller oss sällskap. Vad vill du börja med?", ask: "Skriv till Hildur…", send: "Skicka till Hildur",
    actions: ["Boka rum", "Hantera bokning", "Checka in", "Checka ut", "Boka bastu", "Fråga om Kjell"], tabs: ["Boka", "Min bokning", "In- och utcheckning"],
    bookingHello: "Välkommen upp till fjället! Berätta när du vill komma, så tittar jag i liggaren.", arrival: "Ankomst", departure: "Avresa", guests: "Gäster", availability: "Kontrollera tillgänglighet", next: "Nästa", back: "Tillbaka",
    manageHello: "Har planerna ändrats? Skriv in din bokningsreferens så hjälper jag dig.", reference: "Bokningsreferens", findBooking: "Hämta bokning", checkHello: "Ange ditt rumsnummer så ordnar jag resten.", roomNumber: "Rumsnummer", checkIn: "Checka in", checkOut: "Checka ut",
    seniorMode: "Birgitta-läge", seniorHint: "Större text och en sak i taget", navMenu: "Meny", language: "Språk",
    sauna: "Bastu", saunaSub: "Vedeldad, max 8 personer per pass", breakfast: "Frukost", breakfastSub: "Hjortronsylt, nybakat och rökt röding", aurora: "Norrskenstur", auroraSub: "Guidad kvällstur, 21:00–00:30", issue: "Felanmälan", issueSub: "Något som inte fungerar på rummet?", book: "Boka", yourTime: "Din tid", full: "Fullt", spots: "platser tagna", seating: "Sittning", dietary: "Specialkost eller allergier", reserve: "Reservera bord", date: "Datum", people: "Personer", spotsLeft: "platser kvar ikväll", issueRoom: "Rumsnummer", category: "Kategori", description: "Beskrivning", sendIssue: "Skicka felanmälan",
  },
  no: {
    location: "Hemavan · Sør-Lappland", intro: "Trettåtte rom, en knitrende badstue og fjellet utenfor vinduet. Her møter vi deg med varm fjellgjestfrihet – og katten Kjell.", rooms: "rom", altitude: "moh.", cat: "hotellkatt", guestService: "Gjesteservice", safety: "Trygghet", about: "Om oss", duringStay: "Under oppholdet", privacyTitle: "Opplysningene dine er trygge hos oss", privacyBody: "Hildur passer godt på opplysningene dine. Vi følger GDPR, og du kan alltid be om innsyn eller sletting.", hildurLabel: "Digital resepsjonist", online: "Her hele døgnet", greeting: "Hei! Jeg er Hildur. Jeg tar meg av det praktiske, så Birgitta kan gi deg varm fjellgjestfrihet. Hva kan jeg hjelpe med?", seniorGreeting: "Hei, kjære deg! Vi tar én ting om gangen, rolig og enkelt. Kjell holder oss med selskap.", ask: "Skriv til Hildur…", send: "Send til Hildur", actions: ["Bestill rom", "Håndter bestilling", "Sjekk inn", "Sjekk ut", "Bestill badstue", "Spør om Kjell"], tabs: ["Bestill", "Min bestilling", "Inn- og utsjekk"], bookingHello: "Velkommen til fjellet! Fortell når du vil komme.", arrival: "Ankomst", departure: "Avreise", guests: "Gjester", availability: "Sjekk tilgjengelighet", next: "Neste", back: "Tilbake", manageHello: "Skriv inn bestillingsreferansen, så hjelper jeg deg.", reference: "Bestillingsreferanse", findBooking: "Finn bestilling", checkHello: "Oppgi romnummeret, så ordner jeg resten.", roomNumber: "Romnummer", checkIn: "Sjekk inn", checkOut: "Sjekk ut", seniorMode: "Birgitta-modus", seniorHint: "Større tekst og én ting om gangen", navMenu: "Meny", language: "Språk", sauna: "Badstue", saunaSub: "Vedfyrt, maks 8 personer", breakfast: "Frokost", breakfastSub: "Multebær, nybakt og røkt røye", aurora: "Nordlystur", auroraSub: "Guidet kveldstur, 21:00–00:30", issue: "Meld et problem", issueSub: "Er det noe som ikke virker?", book: "Bestill", yourTime: "Din tid", full: "Fullt", spots: "plasser tatt", seating: "Tid", dietary: "Spesialkost eller allergier", reserve: "Reserver bord", date: "Dato", people: "Personer", spotsLeft: "plasser igjen i kveld", issueRoom: "Romnummer", category: "Kategori", description: "Beskrivelse", sendIssue: "Send melding",
  },
  da: {
    location: "Hemavan · Sydlige Lapland", intro: "Otteogtredive værelser, en knitrende sauna og fjeldet uden for vinduet. Her møder vi dig med varm fjeldgæstfrihed – og katten Kjell.", rooms: "værelser", altitude: "m.o.h.", cat: "hotelkat", guestService: "Gæsteservice", safety: "Tryghed", about: "Om os", duringStay: "Under opholdet", privacyTitle: "Dine oplysninger er trygge hos os", privacyBody: "Hildur passer godt på dine oplysninger. Vi følger GDPR, og du kan altid bede om indsigt eller sletning.", hildurLabel: "Digital receptionist", online: "Her hele døgnet", greeting: "Hej! Jeg er Hildur. Jeg tager mig af det praktiske, så Birgitta kan give dig varm fjeldgæstfrihed. Hvad kan jeg hjælpe med?", seniorGreeting: "Hej med dig! Vi tager én ting ad gangen, roligt og enkelt. Kjell holder os med selskab.", ask: "Skriv til Hildur…", send: "Send til Hildur", actions: ["Book værelse", "Håndter booking", "Tjek ind", "Tjek ud", "Book sauna", "Spørg om Kjell"], tabs: ["Book", "Min booking", "Ind- og udtjekning"], bookingHello: "Velkommen til fjeldet! Fortæl hvornår du vil komme.", arrival: "Ankomst", departure: "Afrejse", guests: "Gæster", availability: "Tjek ledighed", next: "Næste", back: "Tilbage", manageHello: "Skriv din bookingreference, så hjælper jeg dig.", reference: "Bookingreference", findBooking: "Find booking", checkHello: "Skriv dit værelsesnummer, så ordner jeg resten.", roomNumber: "Værelsesnummer", checkIn: "Tjek ind", checkOut: "Tjek ud", seniorMode: "Birgitta-tilstand", seniorHint: "Større tekst og én ting ad gangen", navMenu: "Menu", language: "Sprog", sauna: "Sauna", saunaSub: "Brændefyret, maks. 8 personer", breakfast: "Morgenmad", breakfastSub: "Multebær, nybagt og røget fjeldørred", aurora: "Nordlystur", auroraSub: "Guidet aftentur, 21:00–00:30", issue: "Fejlmelding", issueSub: "Er der noget, som ikke virker?", book: "Book", yourTime: "Din tid", full: "Fuldt", spots: "pladser optaget", seating: "Tid", dietary: "Specialkost eller allergier", reserve: "Reservér bord", date: "Dato", people: "Personer", spotsLeft: "pladser tilbage i aften", issueRoom: "Værelsesnummer", category: "Kategori", description: "Beskrivelse", sendIssue: "Send fejlmelding",
  },
  fi: {
    location: "Hemavan · Etelä-Lappi", intro: "Kolmekymmentäkahdeksan huonetta, lämmin sauna ja tunturi ikkunan takana. Täällä sinut ottaa vastaan lämmin vieraanvaraisuus – ja Kjell-kissa.", rooms: "huonetta", altitude: "m mpy.", cat: "hotellikissa", guestService: "Vieraspalvelut", safety: "Turvallisuus", about: "Meistä", duringStay: "Vierailun aikana", privacyTitle: "Tietosi ovat turvassa", privacyBody: "Hildur pitää tiedoistasi hyvää huolta. Noudatamme GDPR:ää, ja voit aina pyytää tietosi nähtäväksi tai poistettavaksi.", hildurLabel: "Digitaalinen vastaanottovirkailija", online: "Paikalla vuorokauden ympäri", greeting: "Hei! Olen Hildur. Hoidan käytännön asiat, jotta Birgitta voi keskittyä lämpimään vieraanvaraisuuteen. Kuinka voin auttaa?", seniorGreeting: "Hei ystävä! Tehdään yksi asia kerrallaan, rauhassa ja helposti. Kjell pitää meille seuraa.", ask: "Kirjoita Hildurille…", send: "Lähetä Hildurille", actions: ["Varaa huone", "Hallitse varausta", "Kirjaudu sisään", "Kirjaudu ulos", "Varaa sauna", "Kysy Kjellistä"], tabs: ["Varaa", "Varaukseni", "Sisään- ja uloskirjaus"], bookingHello: "Tervetuloa tunturiin! Kerro, milloin haluat tulla.", arrival: "Saapuminen", departure: "Lähtö", guests: "Vieraat", availability: "Tarkista saatavuus", next: "Seuraava", back: "Takaisin", manageHello: "Anna varausnumerosi, niin autan sinua.", reference: "Varausnumero", findBooking: "Hae varaus", checkHello: "Anna huoneesi numero, niin hoidan loput.", roomNumber: "Huoneen numero", checkIn: "Kirjaudu sisään", checkOut: "Kirjaudu ulos", seniorMode: "Birgitta-tila", seniorHint: "Suurempi teksti ja yksi asia kerrallaan", navMenu: "Valikko", language: "Kieli", sauna: "Sauna", saunaSub: "Puulämmitteinen, enintään 8 henkilöä", breakfast: "Aamiainen", breakfastSub: "Hilloja, tuoretta leipää ja savurautua", aurora: "Revontuliretki", auroraSub: "Opastettu iltaretki, 21.00–00.30", issue: "Ilmoita ongelmasta", issueSub: "Eikö jokin toimi huoneessa?", book: "Varaa", yourTime: "Sinun aikasi", full: "Täynnä", spots: "paikkaa varattu", seating: "Aika", dietary: "Erityisruokavalio tai allergiat", reserve: "Varaa pöytä", date: "Päivä", people: "Henkilöt", spotsLeft: "paikkaa jäljellä tänään", issueRoom: "Huoneen numero", category: "Luokka", description: "Kuvaus", sendIssue: "Lähetä ilmoitus",
  },
  en: {
    location: "Hemavan · Southern Lapland", intro: "Thirty-eight rooms, a crackling sauna and the mountain outside your window. We welcome you with warm mountain hospitality – and a cat named Kjell.", rooms: "rooms", altitude: "m above sea", cat: "hotel cat", guestService: "Guest services", safety: "Your safety", about: "About us", duringStay: "During your stay", privacyTitle: "Your information is safe with us", privacyBody: "Hildur looks after your information carefully. We follow GDPR, and you can always ask to view or delete what we keep.", hildurLabel: "Digital receptionist", online: "Here around the clock", greeting: "Hello! I’m Hildur. I handle the practical details so Birgitta can focus on warm mountain hospitality. How may I help?", seniorGreeting: "Hello, dear guest! We’ll take one thing at a time, calmly and simply. Kjell will keep us company.", ask: "Write to Hildur…", send: "Send to Hildur", actions: ["Book a room", "Manage booking", "Check in", "Check out", "Book sauna", "Ask about Kjell"], tabs: ["Book", "My booking", "Check in or out"], bookingHello: "Welcome to the mountain! Tell me when you would like to visit.", arrival: "Arrival", departure: "Departure", guests: "Guests", availability: "Check availability", next: "Next", back: "Back", manageHello: "Enter your booking reference and I’ll help you.", reference: "Booking reference", findBooking: "Find booking", checkHello: "Enter your room number and I’ll take care of the rest.", roomNumber: "Room number", checkIn: "Check in", checkOut: "Check out", seniorMode: "Birgitta mode", seniorHint: "Larger text and one thing at a time", navMenu: "Menu", language: "Language", sauna: "Sauna", saunaSub: "Wood-fired, maximum 8 people", breakfast: "Breakfast", breakfastSub: "Cloudberries, fresh bread and smoked char", aurora: "Northern Lights tour", auroraSub: "Guided evening tour, 21:00–00:30", issue: "Report an issue", issueSub: "Is something not working in your room?", book: "Book", yourTime: "Your time", full: "Full", spots: "spots taken", seating: "Seating time", dietary: "Dietary needs or allergies", reserve: "Reserve table", date: "Date", people: "People", spotsLeft: "spots left tonight", issueRoom: "Room number", category: "Category", description: "Description", sendIssue: "Send report",
  },
};