import { useState } from "react";
import { toast } from "sonner";
import { Coffee, Flame, Moon, Wrench, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { copy, useHotelPreferences } from "./HotelPreferences";

const MAX = 8;
function ServiceCard({ icon: Icon, title, sub, marker, children }: { icon: typeof Flame; title: string; sub: string; marker?: string; children: React.ReactNode }) {
  return <article data-service={marker} className="rounded-md border bg-card p-6 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-md bg-accent text-primary"><Icon/></div><div><h3 className="font-serif text-2xl font-semibold">{title}</h3><p className="text-sm text-muted-foreground">{sub}</p></div></div>{children}</article>;
}
function Sauna() { const {language,senior}=useHotelPreferences(); const c=copy[language]; const [slots,setSlots]=useState<Record<string,number>>({"16:00":3,"17:30":5,"19:00":7,"20:30":2}); const [mine,setMine]=useState<string|null>(null); const times=Object.entries(slots); const [step,setStep]=useState(0); const shown=senior?[times[step]]:times; return <ServiceCard icon={Flame} title={c.sauna} sub={c.saunaSub} marker="sauna"><ul className="space-y-3">{shown.map(([t,n])=><li key={t} className="flex items-center gap-4 rounded-md border p-4"><strong>{t}</strong><div className="flex-1"><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-cloudberry" style={{width:`${n/MAX*100}%`}}/></div><p className="mt-1 text-sm text-muted-foreground">{n}/{MAX} {c.spots}</p></div><Button size="lg" variant={mine===t?"default":"outline"} disabled={n>=MAX&&mine!==t} onClick={()=>{setSlots(s=>({...s,[t]:(s[t]??0)+1}));setMine(t);toast.success(`${c.sauna} ${t}`)}}>{mine===t?c.yourTime:n>=MAX?c.full:c.book}</Button></li>)}</ul>{senior&&step<times.length-1&&<Button className="mt-4 w-full" size="lg" variant="outline" onClick={()=>setStep(step+1)}>{c.next}</Button>}</ServiceCard> }
function Breakfast(){const {language}=useHotelPreferences();const c=copy[language];const [time,setTime]=useState("08:00");return <ServiceCard icon={Coffee} title={c.breakfast} sub={c.breakfastSub}><Label>{c.seating}</Label><div className="my-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{["07:00","08:00","09:00","10:00"].map(t=><Button key={t} variant={time===t?"default":"outline"} onClick={()=>setTime(t)}>{t}</Button>)}</div><Label>{c.dietary}</Label><Textarea className="my-3"/><Button className="w-full" size="lg" onClick={()=>toast.success(`${c.breakfast} ${time}`)}>{c.reserve}</Button></ServiceCard>}
function Aurora(){const {language}=useHotelPreferences();const c=copy[language];const [date,setDate]=useState("");return <ServiceCard icon={Moon} title={c.aurora} sub={c.auroraSub}><p className="mb-4 flex gap-2 text-sm text-muted-foreground"><Users className="h-4 w-4"/>6 {c.spotsLeft}</p><Label>{c.date}</Label><input type="date" className="field my-3" value={date} onChange={e=>setDate(e.target.value)}/><Button className="w-full" size="lg" onClick={()=>date?toast.success(c.aurora):toast.error(c.date)}>{c.book}</Button></ServiceCard>}
function Issue(){const {language}=useHotelPreferences();const c=copy[language];const [room,setRoom]=useState("");return <ServiceCard icon={Wrench} title={c.issue} sub={c.issueSub}><Label>{c.issueRoom}</Label><input className="field my-3" value={room} onChange={e=>setRoom(e.target.value)}/><Label>{c.description}</Label><Textarea className="my-3"/><Button className="w-full" size="lg" variant="outline" onClick={()=>room?toast.success(c.sendIssue):toast.error(c.issueRoom)}>{c.sendIssue}</Button></ServiceCard>}
export function Services(){const {senior}=useHotelPreferences();const [selected,setSelected]=useState(0);const cards=[<Sauna key="s"/>,<Breakfast key="b"/>,<Aurora key="a"/>,<Issue key="i"/>];const c=copy[useHotelPreferences().language];return senior?<div><div className="mb-5 grid gap-2 sm:grid-cols-4">{[c.sauna,c.breakfast,c.aurora,c.issue].map((x,i)=><Button key={x} size="lg" variant={selected===i?"default":"outline"} onClick={()=>setSelected(i)}>{x}</Button>)}</div>{cards[selected]}</div>:<div className="grid gap-5 md:grid-cols-2">{cards}</div>}